server:
  port: 8081
spring:
  application:
    name: goodoog
  profiles:
    active: prod
mybatis-plus:
  type-aliases-package: com.example.goodoog.entity # 别名扫描包
logging:
  level:
    com.example.goodoog: debug
  pattern:
    dateformat: mm:ss.SSS